version: '3'

services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: haradb_new
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  springboot-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8181"
    depends_on:
      - mysql-container
