
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haradb_new?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: madushan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true

application:
  resource:
    devices: devices
    users: users
    roles: roles
    terminals: terminals
    partners: partners
    merchants: merchants
    resources: resources
    userroles: userroles
    permissions: permissions
    rules: rules
    dataTypes: dataTypes
    tables: tables

springdoc:
  api-docs:
    path: /swagger-doc
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    default-models-expand-depth: -1  # this is to remove unwanted tables view in swagger-ui

swagger:
  server:
    url: http://localhost:8080/rule-engine

